title: Curran Hill - Cybersecurity Portfolio
email: curran.hill@protonmail.com
description: Cybersecurity Protfolio
baseurl: ""
url: "https://Curran-Hill.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-spaceship

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

jekyll_spaceship:
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor

  media:
    # Enable Obsidian/MD-style media handling
    enabled: true
    # Treat Obsidian ![[file.png]] as image embeds
    image:
      enabled: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .obsidian
  - Templates
